version: "3.9"

services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  dagster_postgresql:
    image: postgres:11
    container_name: dagster_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - dagster_network

  pipeline_mentalhealth:
    container_name: pipeline_mentalhealth
    image: pipeline_mentalhealth
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "pipeline_mentalhealth"      
    networks:
      - dagster_network
    volumes:
      - /opt/dagster/dagster_home:/tmp/dagster-data
      - /home/shikur/pipeline_mentalhealth/data:/opt/dagster/app/pipeline_mentalhealth/data
 
  
  pipeline_conversation_mentalhealth:
    container_name: pipeline_conversation_mentalhealth
    image: pipeline_conversation_mentalhealth
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "pipeline_conversation_mentalhealth"      
    networks:
      - dagster_network
    volumes:
      - /opt/dagster/dagster_home:/tmp/dagster-data
      - /home/shikur/pipeline_mentalhealth/data:/opt/dagster/app/pipeline_conversation_mentalhealth/data
 
  # This service runs dagster-webserver, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from the webserver will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  dagster_webserver:
    image: dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible, so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./data:/opt/dagster/local/storage
   
    
    networks:
      - dagster_network
    depends_on:
      - dagster_postgresql
      - pipeline_mentalhealth
      - pipeline_conversation_mentalhealth

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  dagster_daemon:
    image: dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      
    volumes: # Make docker client accessible, so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./data:/opt/dagster/app/pipeline_mentalhealth/data
      - /home/shikur/pipeline_mentalhealth/data/output:/opt/dagster/app/pipeline_mentalhealth/data/output
  
           
    networks:
      - dagster_network
    depends_on:
      - dagster_postgresql
      - pipeline_mentalhealth
      - pipeline_conversation_mentalhealth

networks:
  dagster_network:
    driver: bridge
    name: dagster_network

volumes:
  dagster_output:
  
  
    